import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  const [content, setContent] = useState("A Test Announcement");

  const handleClick = async () => {
    try {
      const { data } = await axios.post("/api/hello", {
        content,
      });
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>There will a announcment</p>
        <form>
          <input
            type="text"
            placeholder="Post A Announcement"
            style={{ padding: "5px" }}
            onChange={(e) => setContent(e.target.value)}
          />
        </form>
        <div
          style={{
            border: "1px solid black",
            padding: "3px 10px",
            margin: "10px 5px",
            minWidth: "100px",
            textAlign: "center",
          }}
          onClick={() => handleClick()}
        >
          Post
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
